name: Cypress Tests

on:
  push:
    branches:
      - main

jobs:
  cypress:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: npm run cypress:run

      - name: Upload Mochawesome reports
        uses: actions/upload-artifact@v2
        with:
          name: mochawesome-reports
          path: cypress/reports/mocha

      - name: Upload Screenshots and Videos
        uses: actions/upload-artifact@v2
        with:
          name: cypress-screenshots-videos
          path: cypress/screenshots, cypress/videos
